few_shots = [
    {'Question': "How many gel pens do we have left in blue color?",
     'SQLQuery': "SELECT sum(stock_quantity) FROM pens WHERE type = 'Gel' AND color = 'Blue'",
     'SQLResult': "Result of the SQL query",
     'Answer': "85"},
    {'Question': "How much is the total value of the inventory for all ballpoint pens?",
     'SQLQuery': "SELECT SUM(price*stock_quantity) FROM pens WHERE type = 'Ballpoint'",
     'SQLResult': "Result of the SQL query",
     'Answer': "3542"},
    {'Question': "If we apply a 15% discount to all fountain pens, how much revenue would our store generate?",
     'SQLQuery': """SELECT SUM(price * stock_quantity * 0.85) FROM pens WHERE type = 'Fountain'""",
     'SQLResult': "Result of the SQL query",
     'Answer': "1632.45"},
    {'Question': "How many books are there in the 'Science' genre?",
     'SQLQuery': "SELECT sum(stock_quantity) FROM books WHERE genre = 'Science'",
     'SQLResult': "Result of the SQL query",
     'Answer': "120"},
    {'Question': "How much revenue will our store generate if we sell all biography books today at a 10% discount?",
     'SQLQuery': """SELECT SUM(price * stock_quantity * 0.90) FROM books WHERE genre = 'Biography'""",
     'SQLResult': "Result of the SQL query",
     'Answer': "2700"},
    {'Question': "What is the total stock of rollerball pens in green color?",
     'SQLQuery': "SELECT sum(stock_quantity) FROM pens WHERE type = 'Rollerball' AND color = 'Green'",
     'SQLResult': "Result of the SQL query",
     'Answer': "50"}
]
